version: '3'
services:
  backend:
    image: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    image: react
    ports:
      - "3000:3000"
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
